name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag prosubject:prod
    - name: push to heroku
      env : 
        HEROKU_REGISTRY_URL: registry.heroku.com
        HEROKU_TOKEN : ${{ secrets.HEROKU_TOKEN }}
      run : |
        docker login --username=_ --password $HEROKU_TOKEN $HEROKU_REGISTRY_URL
        export HEROKU_API_KEY=$HEROKU_TOKEN
        heroku container:login
        heroku container:push web --app prosubject-lanzamiento
        heroku container:release web --app prosubject-lanzamiento
        
